site_name: SGNM Notes
site_url: https://CarlosGarayITC.github.io/sgnm-notes/
repo_url: https://github.com/CarlosGarayITC/sgnm-notes
repo_name: sgnm-notes

nav:
  - Home: index.md
  - Quick Start Guide: start-guide.md
  - About this Project: about.md

theme:
  name: material
  palette:
    scheme: default
    primary: deep purple
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.tabs.link
    - header.autohide
  language: en

plugins:
  - search
